# Generated by Django 3.2.19 on 2023-08-22 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=260)),
                ('product_code', models.CharField(max_length=20)),
                ('product_quintity', models.IntegerField(default=0)),
                ('roduct_title', models.CharField(max_length=260)),
                ('product_meterials', models.TextField()),
                ('product_keyword', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='products')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('details', models.TextField()),
                ('lenth', models.CharField(max_length=30)),
                ('Width', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=30)),
                ('main_price', models.IntegerField()),
                ('is_newarival', models.BooleanField(default=False)),
                ('is_discount', models.BooleanField(default=False)),
                ('dic_price', models.IntegerField(blank=True, default=0, null=True)),
                ('cerated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shopApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
