# Generated by Django 3.2.19 on 2023-08-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20230822_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_keyword',
        ),
        migrations.AddField(
            model_name='product',
            name='product_color_image',
            field=models.ImageField(default=1, upload_to='product-color-image'),
            preserve_default=False,
        ),
    ]
