# Generated by Django 3.2.19 on 2023-08-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_auto_20230829_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color_image',
            field=models.ManyToManyField(blank=True, null=True, related_name='colorImg', to='shopApp.ColorImage'),
        ),
    ]
