# Generated by Django 3.2.19 on 2023-08-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=160)),
                ('offer_title', models.CharField(max_length=160)),
                ('offer_description', models.CharField(max_length=260)),
                ('banner_image', models.ImageField(upload_to='bannerimage')),
            ],
        ),
        migrations.CreateModel(
            name='Banner2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=160)),
                ('offer_title', models.CharField(max_length=160)),
                ('offer_description', models.CharField(max_length=260)),
                ('banner_image', models.ImageField(upload_to='bannerimage')),
            ],
        ),
    ]
