# Generated by Django 3.2.21 on 2023-09-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ba', to=settings.AUTH_USER_MODEL),
        ),
    ]
