# Generated by Django 3.2.21 on 2023-09-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_status',
            field=models.BooleanField(default=False),
        ),
    ]
