# Generated by Django 3.2.21 on 2023-09-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_order_delivered_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default='no size selected', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='free size', max_length=50),
        ),
    ]
