# Generated by Django 3.2.21 on 2023-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_auto_20230906_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(default='no color selected', max_length=50),
        ),
    ]
