# Generated by Django 3.2.21 on 2023-09-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0008_cart_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
